tools:
    # Code Coverage
    php_code_coverage:
        enabled:              true
        test_command:         phpunit
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'

