tools:
  php_mess_detector:
    extensions:
      - php
      - inc
  php_code_sniffer:
    config:
      standard: PSR2
    extensions:
      - php
      - inc
  php_cpd:
    names:
      - '*.php'
      - '*.inc'
  php_loc:
    names:
      1: '*.inc'
      2: '*.php'
  php_pdepend:
    suffixes:
      - php
      - inc
  external_code_coverage:
    # Wait up to fifteen minutes for code coverage.
    timeout: 900

checks:
    php:
        code_rating: true
        duplication: true

filter:
  excluded_paths:
    - vendor/*
    - tests/*
    - examples/*
