language: php
php:
  - '7.1'

install:
  - composer global require "hirak/prestissimo:^0.3"
  - composer install
  - composer --no-interaction require codeclimate/php-test-reporter:dev-master

script:
 - >
   ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
 - >
   ./vendor/bin/test-reporter &&
   composer global require theseer/phpdox:dev-master &&
   phpdox


notifications:
  email: false
