language: php
php:
  - '7.1'

install:
  - composer global require "hirak/prestissimo:^0.3"
  - composer install
  - composer --no-interaction require codeclimate/php-test-reporter:dev-master

script:
 - >
   ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
 #- wget https://scrutinizer-ci.com/ocular.phar
 - ./vendor/bin/test-reporter
 #- php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
 - curl http://netcup.gielfeldt.dk:8111/api/build/iterators/$TRAVIS_BRANCH?token=$PHPDOXINIZER_TOKEN

notifications:
  email: false
